# **MÓDULO 20 - Projeto de Credit Score - Naive Bayes**

No módulo 17 vocês realizaram a primeira etapa do projeto de crédito de vocês.
Então fizeram o tratamendo dos dados, balancearam as classes, transformaram as variáveis categóricas e separam base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

**IMPORTANTE:** Não se esqueçam de ao enviar o código de vocês para os tutores, enviarem as bases, pois como cada um de vocês realizou as alterações de tratamento indidualmente o tutor precisa ter acesso aos seus dados individuais.

In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
import plotly.figure_factory as ff

Durante a aula nossa variável a ser prevista (churn) continha apenas 2 categorias, a base de vocês contém mais. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária. O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.
Em resumo, o Naive Bayes pode ser aplicado da mesma maneira para problemas de classificação com múltiplas classes, e os mesmos princípios se aplicam em termos de treinamento, avaliação e aplicação do modelo.

# 1) Comece carregando as bases de treino (X e y) e teste (X e y).
Verifique se o número de linhas condiz, se as variáveis estão corretas sendo apenas a de score para y e as demais nas bases de X e por último, se Y está balanceada no teste.

In [4]:
X_test = pd.read_csv("X_test_Credit_Score_Parte2.csv", delimiter=',')
X_train = pd.read_csv("X_train_Credit_Score_Parte2.csv", delimiter=',')
y_test = pd.read_csv("y_test_Credit_Score_Parte2.csv", delimiter=',')
y_train = pd.read_csv("y_train_Credit_Score_Parte2.csv", delimiter=',')

In [5]:
X_test

,Age,Income,Number of Children,Gender_Male,Education_Bachelor's Degree,Education_Doctorate,Education_High School Diploma,Education_Master's Degree,Marital Status_Single,Home Ownership_Rented
0,25,55000.0,0,False,True,False,False,False,True,True
1,48,87500.0,1,False,False,True,False,False,False,False
2,26,55000.0,1,False,True,False,False,False,False,False
3,39,62500.0,2,False,True,False,False,False,False,False
4,35,90000.0,1,False,False,True,False,False,False,False
5,25,55000.0,0,False,True,False,False,False,True,True
6,48,82500.0,1,False,False,True,False,False,False,False
7,48,82500.0,1,False,False,True,False,False,False,False
8,36,95000.0,2,False,False,False,False,True,False,False
9,38,95000.0,1,False,False,False,True,False,False,False
10,38,50000.0,0,True,False,False,True,False,True,True
11,38,27500.0,0,False,False,False,True,False,True,True
12,38,95000.0,0,True,False,False,False,True,True,False
13,50,160000.0,0,True,False,False,False,True,False,False
14,29,25000.0,0,False,False,False,True,False,True,True
15,30,105000.0,2,True,False,False,False,True,False,False
16,32,85000.0,0,True,False,False,False,True,True,True
17,27,37500.0,0,False,False,False,True,False,True,True
18,38,130000.0,0,True,False,False,True,False,False,False
19,38,85000.0,1,False,False,True,False,False,False,False
20,37,75000.0,2,False,True,False,False,False,False,False
21,38,30000.0,0,False,False,False,False,False,True,True
22,38,35000.0,0,False,False,False,True,False,True,True
23,38,105000.0,0,True,False,True,False,False,True,False
24,35,80000.0,1,False,False,True,False,False,False,False
25,38,67500.0,2,False,True,False,False,False,False,False
26,50,162500.0,0,True,False,False,False,True,False,False
27,44,87500.0,0,True,False,False,False,True,True,False
28,34,105000.0,1,True,True,False,False,False,False,True
29,34,47500.0,0,True,False,False,False,False,True,True
30,45,105000.0,3,False,True,False,False,False,False,False
31,52,135000.0,0,True,False,False,True,False,False,False
32,35,85000.0,1,False,False,True,False,False,False,False

In [6]:
y_test

   Credit Score
0       Average
1          High
2       Average
3          High
4          High
5       Average
6          High
7          High
8          High
9          High
10      Average
11          Low
12         High
13         High
14          Low
15         High
16         High
17          Low
18         High
19         High
20         High
21          Low
22          Low
23         High
24         High
25         High
26         High
27         High
28         High
29      Average
30         High
31         High
32         High

In [7]:
y_train

    Credit Score
0           High
1           High
2           High
3           High
4        Average
..           ...
265          Low
266          Low
267          Low
268          Low
269          Low

[270 rows x 1 columns]

In [8]:
X_train

,Age,Income,Number of Children,Gender_Male,Education_Bachelor's Degree,Education_Doctorate,Education_High School Diploma,Education_Master's Degree,Marital Status_Single,Home Ownership_Rented
0,38,125000.000000,0,True,False,False,False,False,False,False
1,35,75000.000000,1,False,False,True,False,False,False,False
2,30,117500.000000,2,True,False,False,False,True,False,False
3,47,90000.000000,1,False,False,True,False,False,False,False
4,32,57500.000000,0,True,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...
265,27,37500.000000,0,False,False,False,True,False,True,True
266,27,36900.673163,0,False,False,False,True,False,True,True
267,28,32500.000000,0,False,False,False,False,False,True,True
268,28,32785.451480,0,False,False,False,True,False,True,True
269,27,35883.985340,0,False,False,False,True,False,True,True

In [9]:
train_balance = y_train.value_counts()
print("Balanceamento em y_train:")
print(train_balance)

# Contar o número de exemplos de cada classe em y_test
test_balance = y_test.value_counts()
print("\nBalanceamento em y_test:")
print(test_balance)

Balanceamento em y_train:
Credit Score
High            90
Average         90
Low             90
Name: count, dtype: int64

Balanceamento em y_test:
Credit Score
High            23
Average          5
Low              5
Name: count, dtype: int64

# 2) Aplique o algoritmo de Naive Bayes aos dados de treinamento.

In [10]:
naive_churn = GaussianNB()

naive_churn.fit(X_train, y_train)

C:\Users\victo\Desktop\EBAC Projetos\.venv\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

# 3) Faça a avaliação do modelo com os dados de treinamento.
Traga a acurácia, recall e plote a matriz de confusão. Não se esqueça de avaliar com suas palavras o desempenho do modelo, interpretando as métricas.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

In [12]:
y_pred_train = naive_churn.predict(X_train)
accuracy = accuracy_score(y_train, y_pred_train)
recall = recall_score(y_train, y_pred_train, average='macro')
print("Acurácia:", accuracy)
print("Recall:", recall)

Acurácia: 0.9814814814814815
Recall: 0.9814814814814815

In [15]:
conf_matrix = confusion_matrix(y_train, y_pred_train)

class_names = ['High Score', 'Avarege Score', 'Low Score']

# Plotando a matriz de confusão com Plotly
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=class_names,
    y=class_names,
    colorscale='Blues',
    showscale=True
)
fig.update_layout(
    title='Matriz de Confusão',
    xaxis_title='Predicted labels',
    yaxis_title='True labels',
    font=dict(
        family='Arial',
        size=12,
        color='black'
    )
)

# 4) Aplique o modelo aos dados de teste e realize a avaliação dos resultados, da mesma forma que fez acima. Não se esqueça de avaliar com as suas palavras e comparar o desempenho da base treino com a teste.

In [18]:
naive_churn.fit(X_test, y_test)

C:\Users\victo\Desktop\EBAC Projetos\.venv\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [20]:
y_pred_test = naive_churn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_test)
recall = recall_score(y_test, y_pred_test, average='macro')
print("Acurácia:", accuracy)
print("Recall:", recall)

Acurácia: 1.0
Recall: 1.0

In [17]:

conf_matrix = confusion_matrix(y_test, y_pred_test)

class_names = ['High Score', 'Avarege Score', 'Low Score']

# Plotando a matriz de confusão com Plotly
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=class_names,
    y=class_names,
    colorscale='Blues',
    showscale=True
)
fig.update_layout(
    title='Matriz de Confusão',
    xaxis_title='Predicted labels',
    yaxis_title='True labels',
    font=dict(
        family='Arial',
        size=12,
        color='black'
    )
)

O modelo apresentou um desempenho excelente na base de treino e um desempenho perfeito na avaliação de métricas da base de teste. Na prática de Machine Learning, é esperado que o desempenho no teste sofra uma leve queda em relação ao treino; um resultado cravado em 100% no teste pode indicar que a base separada para teste é muito pequena, possui padrões idênticos aos do treino

A matriz revela que o modelo aprendeu muito bem os padrões, acertando a esmagadora maioria das classificações na diagonal principal: 88 acertos para "High Score", 89 para "Avarege Score" e 88 para "Low Score". Os erros foram marginais, como, por exemplo, classificar erroneamente 2 casos reais de "Low Score" como "High Score".

Analisando a segunda matriz gerada, o modelo acertou 5 casos reais de "High Score", 23 de "Avarege Score" e 2 de "Low Score". Apesar do bom volume de acertos no "Avarege Score", a matriz revela que o modelo cometeu alguns erros, como prever que 2 casos reais de "Low Score" eram "Avarege Score" e 1 caso real de "Low Score" era "High Score".

# 5) Descreva com suas palavras o projeto desenvolvido nessa atividade e qual o nosso objetivo principal ao aplicarmos o algoritmo de naive bayes a base de crédito.
Utilize pelo menos 4 linhas.

Dica: Caso você ainda esteja tendo dificuldade em visualizar a aplicação dos projetos e objetivo, consulte seus tutores!

O nosso objetivo principal ao aplicar o algoritmo de Naive Bayes a essa base de crédito é prever de forma automática e probabilística a categoria de pontuação de novos clientes. O projeto desenvolvido nesta atividade consiste na construção de um sistema de avaliação de risco financeiro empregando técnicas de aprendizado de máquina (Machine Learning). A partir de uma base de dados históricos contendo as características e os perfis de diversos clientes, estruturamos os dados.